arabold/docs-mcp-server

src/store/DocumentStore.test.ts
src/store/DocumentStore.ts

Adds escaping for the full-text search query in DocumentStore.findByContent to prevent errors and ensure correct search behavior when the query contains special characters like quotes, parentheses, or FTS operators.
Also adds unit tests to verify the escaping logic.
Fixes #10

fix(store): escape FTS query to handle special characters

---

.clinerules
.env.example
ARCHITECTURE.md
Dockerfile
README.md
package-lock.json
package.json
src/store/DocumentStore.test.ts
src/store/DocumentStore.ts
src/store/embeddings/EmbeddingFactory.test.ts
src/store/embeddings/EmbeddingFactory.ts
src/store/embeddings/FixedDimensionEmbeddings.test.ts
src/store/embeddings/FixedDimensionEmbeddings.ts
src/store/schema.ts

This change introduces support for multiple embedding model providers beyond the default OpenAI, allowing users to configure providers like Google Vertex AI, Google Gemini, AWS Bedrock, and Azure OpenAI via the `DOCS_MCP_EMBEDDING_MODEL` environment variable.
**Key Changes:**
*   **Embedding Factory (`EmbeddingFactory.ts`):**
*   Refactored to dynamically instantiate LangChain embedding classes based on the specified provider
*   Added support for `vertex`, `gemini`, `aws`, and `microsoft` providers
*   Includes checks for required environment variables per provider
*   **Dimension Handling (`FixedDimensionEmbeddings.ts`):**
*   Introduced a new `FixedDimensionEmbeddings` wrapper class
*   This wrapper ensures all vectors match the database's fixed dimension (1536)
*   Pads vectors …

feat(embeddings): add support for multiple embedding providers

---

.github/workflows/release.yml
README.md

This change modifies our release workflow to be manually triggered instead of automatically running on every merge to main. This allows us to batch multiple PRs together before creating a new release.
Changes:
- Renamed publish.yml to release.yml for consistency
- Changed workflow trigger from push to workflow_dispatch
- Updated README.md to reflect manual release process
This gives us more control over when releases are created, allowing us to merge multiple PRs before deciding to create a new release.

chore: switch release workflow to manual trigger

---

src/mcp/index.ts
src/tools/SearchTool.test.ts
src/tools/SearchTool.ts

- remove exactMatch flag from the MCP server interface to prevent confusion for LLM/API users
- keep exactMatch logic for CLI/internal use, now robustly throws VersionNotFoundError with available versions if used without a version
- add and update unit tests for all exactMatch scenarios
resolves #24

fix(search): remove exactMatch flag from MCP API, improve internal handling

---

src/store/DocumentManagementService.test.ts
src/store/DocumentManagementService.ts

Fixes an issue where the database store path was not being resolved correctly when the current working directory was not the project root.
- Use `import.meta.dirname` for proper path resolution
- Implement store path resolution priority:
1. Environment variable (`DOCS_MCP_STORE_PATH`)
2. Legacy path (.store in project root)
3. Standard system path
- Ensure database directory exists before initialization
Verified that the store path is correctly resolved regardless of the current working directory:
- When running from project root
- When running from a subdirectory
- When using environment variable override
- When using legacy path

fix: resolve store path correctly when not in project root

---

src/scraper/processor/HtmlProcessor.ts

This PR fixes the HTML to Markdown conversion bug by removing overly aggressive filtering that was causing content loss.
Changes:
- Removes `figure` and `sup` tags from HTML filtering to preserve important content like diagrams and footnotes
- Keeps `.alert` and `[role="alert"]` selectors commented out since they often contain important content
- Adds explanatory comments about alerts being used for important content
Fixes #36

fix: remove overly aggressive html filtering

---

src/scraper/processor/HtmlProcessor.ts

Line breaks were being lost when processing pre tags due to improper text content extraction. This fix implements a custom logic that preserves line breaks by properly handling br tags.
- Modified the pre tag handling in HtmlProcessor to properly handle line breaks
- Added logic to preserve br tags during content extraction

fix: preserve line breaks in pre tags during HTML processing

---

src/store/DocumentManagementService.ts

This PR removes an unnecessary debug log output that was accidentally left in the DocumentManagementService code.

chore: remove debug log output from DocumentManagementService

---

src/scraper/processor/HtmlProcessor.test.ts
src/scraper/processor/HtmlProcessor.ts

Replaces the fragile regex-based title extraction in HtmlProcessor with the more robust window.document.title property provided by JSDOM.
This correctly handles cases where the <title> tag contains attributes.
Adds a test case to verify title extraction with attributes.
Fixes #41

fix(scraper): use JSDOM title property for robust HTML title extraction

---

README.md
src/cli.ts
src/config.ts
src/mcp/index.ts
src/tools/ScrapeTool.test.ts
src/tools/ScrapeTool.ts

This PR increases the default value for `maxPages` from 100 to 1000 to improve the out-of-the-box experience for users scraping larger documentation sites.
- Create `config.ts` with shared configuration constants:
```typescript
export const DEFAULT_MAX_PAGES = 1000;
export const DEFAULT_MAX_DEPTH = 3;
export const DEFAULT_MAX_CONCURRENCY = 3;
```
- Use these constants consistently across:
- CLI configuration
- ScrapeTool implementation
- MCP server tool schema
- Update parameter descriptions to include default values
- Add proper documentation for these values in the README
- Fixed potential issue with maxConcurrency handling in ScrapeTool
Closes #43

feat: increase default maxPages and centralize configuration constants

---

src/scraper/middleware/components/HtmlJsExecutorMiddleware.test.ts
src/scraper/middleware/components/HtmlJsExecutorMiddleware.ts
src/scraper/middleware/components/index.ts
src/scraper/middleware/types.ts
src/scraper/strategies/WebScraperStrategy.ts
src/scraper/types.ts
src/scraper/utils/sandbox.test.ts
src/scraper/utils/sandbox.ts
src/tools/FetchUrlTool.ts

Implements the `HtmlJsExecutorMiddleware` which uses a Node.js vm sandbox (via `executeJsInSandbox`) to execute JavaScript found in HTML content.
Includes:
- Initial implementation of the middleware.
- Addition of external script fetching via a secure callback mechanism using the context fetcher.
- Updated unit tests for both the sandbox utility and the middleware, including fixes and tests for external script handling.
- Added a documentation warning (`@remarks`) to `HtmlJsExecutorMiddleware` highlighting its limitations regarding full Web API support and browser execution fidelity, recommending against general production use.
Closes #18

feat(scraper): Implement HtmlJsExecutorMiddleware with sandbox (#18)

---

src/scraper/middleware/components/HtmlDomParserMiddleware.ts
src/scraper/middleware/components/HtmlJsExecutorMiddleware.ts
src/scraper/middleware/components/HtmlMetadataExtractorMiddleware.test.ts
src/scraper/middleware/components/HtmlPlaywrightMiddleware.ts
src/scraper/utils/sandbox.ts
src/splitter/SemanticMarkdownSplitter.ts
src/utils/dom.ts

Replaces direct JSDOM instantiation with a factory function that configures a silent virtual console by default.
Fixes #53

fix: silence JSDOM virtual console output

---

src/scraper/middleware/components/HtmlPlaywrightMiddleware.ts

This PR addresses issue #62 by changing the Playwright wait condition from `domcontentloaded` to `load`.
Fixes #62

fix(scraper): replace domcontentloaded with load event in Playwright

---

src/scraper/middleware/components/HtmlToMarkdownMiddleware.test.ts
src/scraper/middleware/components/HtmlToMarkdownMiddleware.ts

This PR adds a custom rule to remove empty and invalid anchor links during HTML to Markdown conversion and includes a test case to validate the behavior.

feat: remove empty anchor links in HtmlToMarkdownMiddleware

---

src/store/DocumentRetrieverService.test.ts
src/store/DocumentRetrieverService.ts
src/store/DocumentStore.test.ts
src/store/DocumentStore.ts

Refactored DocumentRetrieverService to group initial hits by URL, deduplicate and merge context, and produce a single ordered result per URL. Includes updated and new unit tests for DocumentStore and DocumentRetrieverService. Removes outdated per-hit aggregation tests and replaces with focused, scenario-based tests for the new logic.

Consolidate search results by URL in DocumentRetrieverService (closes #46)

---

src/splitter/GreedySplitter.test.ts
src/splitter/GreedySplitter.ts
src/splitter/SemanticMarkdownSplitter.test.ts
src/splitter/SemanticMarkdownSplitter.ts
src/splitter/splitters/CodeContentSplitter.test.ts
src/splitter/splitters/CodeContentSplitter.ts
src/splitter/splitters/TableContentSplitter.test.ts
src/splitter/splitters/TableContentSplitter.ts
src/splitter/splitters/TextContentSplitter.test.ts
src/splitter/splitters/TextContentSplitter.ts
src/splitter/splitters/types.ts
src/store/DocumentManagementService.ts
src/utils/config.ts

This PR addresses #1 by:
- Distinguishing between `minChunkSize`, `preferredChunkSize`, and `maxChunkSize` for chunk splitting
- Refactoring splitters and related logic to use the new parameters
- Updating tests and configuration to reflect new chunk size handling
- Ensuring no chunk exceeds `maxChunkSize` and small chunks are dropped as specified
Closes #1.

Introduce minChunkSize, preferredChunkSize, and maxChunkSize parameters (#1)

---

src/store/DocumentStore.ts

Fixes #82: When running the MCP server in Docker, it fails during startup with the error:
"Failed to apply migration: 000-initial-schema.sql - SqliteError: no such module: vec0"
This happens because the migration script tries to use the `vec0` SQLite module before it's loaded.
Reordered the initialization sequence in `DocumentStore.initialize()` to load the SQLite vector extension before applying migrations, ensuring the `vec0` module is available when needed by the migration scripts.
- Modified the `initialize()` method in `DocumentStore` class to load SQLite extensions before running migrations
- Verified the server starts correctly without the "no such module: vec0" error
- Confirmed that document storage and retrieval functionality works as expected

Fix: Load SQLite vector extension before applying migrations

---

src/store/DocumentStore.ts
src/utils/config.ts

This PR introduces a batch limit for embedding creation in DocumentStore to prevent token limit errors when processing large numbers of documents. The batch size is configurable via EMBEDDING_BATCH_SIZE in src/utils/config.ts. Closes #93.

fix(store): batch embedding creation to avoid token limit errors (closes #93)

---

src/store/embeddings/EmbeddingFactory.ts

This PR fixes an issue where model names containing a colon (`:`) were not parsed correctly in the embedding model factory. Now, the model name is properly reconstructed if it contains colons. Closes #89.

fix(embeddings): handle colon in model name parsing (#89)

---

src/web/components/Layout.tsx
vite.config.ts
vite.config.web.ts

- Injects __APP_VERSION__ at build time in both vite configs
- Layout component shows version next to title, aligned baseline
- Improves traceability and user awareness of deployed version
This PR adds the build version to the UI title, making it visible to users and maintainers.

Display build version in UI title using __APP_VERSION__ from package.json

---

src/store/applyMigrations.ts
src/utils/config.ts

Resolves #108 by ensuring the entire migration process, including reading the current migration state, is wrapped in an IMMEDIATE database transaction. This provides atomicity and helps prevent race conditions if multiple application instances attempt to run migrations simultaneously.
Also implements an async retry mechanism for SQLITE_BUSY errors, allowing the migration to attempt acquiring a database lock multiple times with a delay.

fix(store): wrap migrations in immediate transaction with retries

---

src/web/components/VersionDetailsRow.tsx

This PR fixes the issue where deleting documentation for libraries with special characters (such as scoped packages) would fail in the web UI. The following changes were made:
- Sanitize library name and version for row IDs and hx-target selectors
- Use encodeURIComponent for DELETE URLs to support scoped packages and special characters
**Fixes GitHub Task #100: can't delete docs via web UI**
---
Please review and merge if approved.

fix(web): sanitize and encode library/version for delete (fixes #100)

---

package-lock.json
package.json
src/index.ts
src/scraper/strategies/BaseScraperStrategy.test.ts
src/scraper/strategies/BaseScraperStrategy.ts
src/scraper/types.ts
src/scraper/utils/patternMatcher.test.ts
src/scraper/utils/patternMatcher.ts
src/scraper/utils/scope.test.ts
src/scraper/utils/scope.ts
src/tools/ScrapeTool.ts
src/web/components/ScrapeFormContent.tsx
src/web/components/Tooltip.tsx
src/web/routes/jobs/new.tsx

This PR implements robust URL filtering for the documentation scraping pipeline, CLI, and web interface.
- Adds support for glob and regex include/exclude patterns (with auto-detection and precedence)
- Updates CLI and web UI to accept and document these options
- Ensures options are parsed, passed, and tested end-to-end
- Refactors pattern matching utilities to use minimatch for glob support
- Adds and updates unit/integration tests for filtering logic
Closes #97.

feat(scraper): add robust URL filtering with glob/regex patterns (closes #97)

---

src/scraper/middleware/HtmlPlaywrightMiddleware.test.ts
src/scraper/middleware/HtmlPlaywrightMiddleware.ts
src/scraper/strategies/WebScraperStrategy.test.ts

This PR improves the reliability of Playwright-based page loading in the web scraper middleware and tightens the associated unit tests.
- Waits for the `body` selector after navigation to ensure the DOM is ready before extracting content, making scraping more robust for both authenticated and non-authenticated sites.
- Updates tests to mock `waitForSelector` and assert that no errors are added to `context.errors` in the credentialed URL scenario.
- Fixes navigation/content extraction issues seen on some authenticated sites.
- Ensures tests are robust and reflect real middleware behavior.
Refs #116
---
**Files changed:**
- `src/scraper/middleware/HtmlPlaywrightMiddleware.ts`
- `src/scraper/middleware/HtmlPlaywrightMiddleware.test.ts`
Please review and merge if all looks good!

feat(scraper/playwright): improve Playwright page loading reliability and test robustness (#116)

---

.github/workflows/ci.yml
Dockerfile
README.md
package.json
src/index.ts

- Install Playwright browsers only in test job and Docker build
- Remove unconditional install from postinstall script
- Add README note for local devs
This reduces CI/CD time and avoids unnecessary installs.

chore(ci): install Playwright browsers only when needed

---

.github/workflows/release.yml
README.md

Closes #127
- The release workflow now builds and pushes Docker images for both linux/amd64 and linux/arm64 platforms using Docker Buildx.
- Updated README to note support for both Intel and Apple Silicon Macs.
This enables native Docker usage on both Intel and Apple Silicon Macs via the published images.

feat(ci): publish multi-arch Docker images (x86_64/amd64 and arm64) for Mac Silicon support

---

Dockerfile
src/index.ts
src/scraper/middleware/HtmlPlaywrightMiddleware.ts

Closes #124. This PR reduces the Docker image size by installing system Chromium via apt-get and configuring Playwright to use it via the PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH environment variable. The HtmlPlaywrightMiddleware now explicitly uses this path if set. This avoids downloading Playwright's own browser build and ensures a smaller, more efficient image.

feat(docker): use system Chromium instead of Playwright's bundled browser

---

package-lock.json
src/mcp/tools.ts
src/pipeline/PipelineManager.ts
src/pipeline/PipelineWorker.test.ts
src/pipeline/PipelineWorker.ts
src/scraper/fetcher/HttpFetcher.ts
src/tools/ClearCompletedJobsTool.test.ts
src/tools/ClearCompletedJobsTool.ts
src/tools/index.ts
src/web/components/JobItem.tsx
src/web/components/JobList.tsx
src/web/components/LibraryDetailCard.tsx
src/web/components/LibraryItem.tsx
src/web/components/LibrarySearchCard.tsx
src/web/components/VersionDetailsRow.tsx
src/web/main.client.ts
src/web/routes/index.tsx
src/web/routes/jobs/cancel.tsx
src/web/routes/jobs/clear-completed.tsx
src/web/web.ts

- Properly resolves `waitForJobCompletion` for cancelled jobs, allowing document deletion to complete without error.
- Ensures RemoveTool and web interface can reliably delete library versions even if jobs are running or queued.
- Adds a robust, flicker-free "Clear Completed Jobs" button using idiomatic HTMX (hx-post, hx-swap="none"), positioned right of the "Job Queue" title.
- Button only refreshes the job list (not the whole page or other sections) and removes unnecessary custom event logic.
- Implements `/api/jobs/clear-completed` API route and `ClearCompletedJobsTool` for backend job cleanup.
- Instantly refreshes the libraries/versions list in the web UI after a successful delete, improving user experience.
- Adds endpoint and UI logic to stop a scraping job from the web interface. …

fix(pipeline, ui): add 'Remove Completed Jobs' feature, robust job cancel, and improve HTMX/Alpine integration (fixes #137)

---

.env.example
src/store/DocumentStore.ts
src/utils/config.ts

This PR fixes the "413 Request entity too large" error that occurs when processing large documents with many chunks, such as the Telegram API changelog.
When indexing large documents like https://core.telegram.org/bots/api-changelog, the following error occurs:
```
❌ [6bc64f77-bc0a-4626-8dbf-6a8e39956b18] Failed to store document https://core.telegram.org/bots/api-changelog: ConnectionError: Failed to add documents to store caused by Error: 413 Request entity too large
⚠️ Job 6bc64f77-bc0a-4626-8dbf-6a8e39956b18 error on document https://core.telegram.org/bots/api-changelog: Failed to add documents to store caused by Error: 413 Request entity too large
```
The issue is that the embedding API (OpenAI, Together.ai, etc.) has request size limits, and we were exceeding them by sending too …

fix: prevent 413 errors when embedding large documents

---

src/scraper/middleware/HtmlPlaywrightMiddleware.test.ts
src/scraper/middleware/HtmlPlaywrightMiddleware.ts

Enhance the loading handling for iframes and improve loading indicator checks in the Playwright middleware. This update allows the fetch-url tool to extract meaningful content from embedded iframes on HuggingFace Spaces pages, ensuring comprehensive content indexing. The solution addresses dynamic loading issues and optimizes resource loading while maintaining existing functionality for non-iframe pages. Closes #194

Fix iframe content extraction for HuggingFace Spaces URLs

---

Dockerfile
README.md
docker-compose.yml
src/app/AppServer.test.ts
src/app/AppServer.ts
src/app/AppServerConfig.ts
src/cli/commands/default.ts
src/cli/commands/mcp.ts
src/cli/commands/web.ts
src/cli/commands/worker.ts
src/cli/utils.ts
src/scraper/ScraperRegistry.test.ts
src/scraper/pipelines/HtmlPipeline.charset.test.ts
src/scraper/pipelines/HtmlPipeline.test.ts
src/scraper/strategies/WebScraperStrategy.test.ts
src/store/DocumentManagementService.test.ts
src/tools/FetchUrlTool.test.ts
src/utils/config.ts

Introduce a host configuration option for server binding, allowing users to specify the host address for the application. Update the Dockerfile, application server, and CLI commands accordingly.

Add host configuration for server binding
